package com.chatcrmlite.backend.models;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Stores tenant-defined custom menu cards for the chat widget sidebar.
 * When a tenant has rows here for a given section, those override the
 * niche-default cards generated by NicheThemeService.
 */
@Entity
@Table(name = "custom_menu_cards",
       indexes = @Index(name = "idx_custom_menu_cards_tenant", columnList = "tenant_id"))
public class CustomMenuCard {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tenant_id", nullable = false)
    private Tenant tenant;

    /** Section bucket: SERVICES, RESOURCES, CONNECT (uppercase) */
    @Column(nullable = false, length = 50)
    private String section = "SERVICES";

    @Column(nullable = false, length = 80)
    private String title;

    @Column(length = 120)
    private String subtitle;

    /** Icon key mapped in the widget JS (calendar, briefcase, home, info, doc, etc.) */
    @Column(length = 40)
    private String icon = "briefcase";

    /**
     * Action type:
     *  FLOW     — triggers a built-in flow (appointment/booking/lead)
     *  CATALOG  — opens the product/service catalog
     *  ABOUT    — shows the tenant's "About Us" text
     *  SUPPORT  — opens the support ticket form
     *  LINK     — opens an external URL
     */
    @Column(name = "action_type", nullable = false, length = 20)
    private String actionType = "CATALOG";

    /**
     * Payload depends on actionType:
     *  FLOW   → "appointment" | "booking" | "lead"
     *  LINK   → "https://..."
     *  Others → "" or ignored
     */
    @Column(name = "action_payload", length = 500)
    private String actionPayload = "";

    /** Controls order within a section — lower number appears first */
    @Column(name = "display_order", nullable = false)
    private Integer displayOrder = 0;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    public CustomMenuCard() {}

    // ── Getters & Setters ────────────────────────────────────────────────────

    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public Tenant getTenant() { return tenant; }
    public void setTenant(Tenant tenant) { this.tenant = tenant; }

    public String getSection() { return section; }
    public void setSection(String section) { this.section = section; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getSubtitle() { return subtitle; }
    public void setSubtitle(String subtitle) { this.subtitle = subtitle; }

    public String getIcon() { return icon; }
    public void setIcon(String icon) { this.icon = icon; }

    public String getActionType() { return actionType; }
    public void setActionType(String actionType) { this.actionType = actionType; }

    public String getActionPayload() { return actionPayload; }
    public void setActionPayload(String actionPayload) { this.actionPayload = actionPayload; }

    public Integer getDisplayOrder() { return displayOrder; }
    public void setDisplayOrder(Integer displayOrder) { this.displayOrder = displayOrder; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
