package com.chatcrmlite.backend.services;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Deterministic High-Precision Evidence Grounding & Hallucination Detector.
 * 
 * Verifies that high-confidence factual claims generated by the LLM (prices, numbers,
 * operating schedules, phone numbers, emails, URLs, and named entities) are strictly
 * supported by the retrieved RAG context.
 */
@Slf4j
@Component
public class HallucinationDetector {

    private static final List<String> UNKNOWN_PHRASES = List.of(
        "i don't know",
        "i don't have that information",
        "not mentioned in the context",
        "i'm sorry, but i cannot",
        "the provided context does not contain",
        "i do not have access",
        "not provided in the context"
    );

    private static final List<String> HEDGING_PHRASES = List.of(
        "it is possible",
        "i think",
        "maybe",
        "perhaps",
        "i am not sure",
        "it seems like",
        "could possibly be"
    );

    private static final List<String> DAYS_OF_WEEK = List.of(
        "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"
    );

    private static final List<String> MAJOR_CITIES = List.of(
        "delhi", "mumbai", "bangalore", "bengaluru", "kolkata", "chennai", "hyderabad",
        "pune", "ahmedabad", "jaipur", "lucknow", "chandigarh", "new york", "london",
        "san francisco", "chicago", "los angeles", "toronto", "dubai", "singapore"
    );

    private static final Map<String, Integer> WORD_TO_NUMBER = Map.ofEntries(
        Map.entry("zero", 0), Map.entry("one", 1), Map.entry("two", 2), Map.entry("three", 3),
        Map.entry("four", 4), Map.entry("five", 5), Map.entry("six", 6), Map.entry("seven", 7),
        Map.entry("eight", 8), Map.entry("nine", 9), Map.entry("ten", 10),
        Map.entry("twenty", 20), Map.entry("thirty", 30), Map.entry("forty", 40),
        Map.entry("fifty", 50), Map.entry("sixty", 60), Map.entry("seventy", 70),
        Map.entry("eighty", 80), Map.entry("ninety", 90), Map.entry("hundred", 100),
        Map.entry("five hundred", 500), Map.entry("thousand", 1000), Map.entry("one thousand", 1000)
    );

    // Regex Patterns
    private static final Pattern PHONE_PATTERN = Pattern.compile("(?:\\+?\\d{1,3}[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}|\\b\\d{10}\\b");
    private static final Pattern EMAIL_PATTERN = Pattern.compile("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}");
    private static final Pattern URL_PATTERN = Pattern.compile("https?://[^\\s/$.?#].[^\\s]*|www\\.[^\\s/$.?#].[^\\s]*");
    private static final Pattern TIME_PATTERN = Pattern.compile("\\b(0?[1-9]|1[0-2])(?::([0-5][0-9]))?\\s*(am|pm|a\\.m\\.|p\\.m\\.)\\b|\\b([01]?[0-9]|2[0-3]):([0-5][0-9])\\b|\\b(0?[1-9]|1[0-2])\\s+in\\s+the\\s+(morning|evening|afternoon|night)\\b", Pattern.CASE_INSENSITIVE);
    private static final Pattern CURRENCY_NUMBER_PATTERN = Pattern.compile("(?:₹|Rs\\.?|INR|\\$|USD)?\\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]+)?|[0-9]+(?:\\.[0-9]+)?)\\s*(?:₹|Rs\\.?|INR|\\$|USD|dollars?|rupees?|bucks?)?", Pattern.CASE_INSENSITIVE);
    private static final Pattern DOCTOR_ENTITY_PATTERN = Pattern.compile("\\b(?:Dr\\.|Doctor|Mr\\.|Mrs\\.|Ms\\.)\\s+([A-Z][a-z]+(?:\\s+[A-Z][a-z]+)?)\\b");

    /**
     * Evaluates if a response is grounded in the retrieved context.
     * 
     * @param response The LLM generated response
     * @param context  The retrieved RAG context chunks
     * @return true if the response is valid and grounded, false if ungrounded/hallucinated
     */
    public boolean isValid(String response, String context) {
        if (response == null || response.isBlank()) {
            return false;
        }

        // 1. Check for pure fallback / unknown response
        if (isUnknownOrRefusal(response)) {
            log.info("[HallucinationDetector] Model refusal / unknown response detected.");
            return false;
        }

        // 2. Check for excessive hedging (low confidence)
        if (isExcessiveHedging(response)) {
            log.warn("[HallucinationDetector] High hedging detected. Possible low confidence.");
            return false;
        }

        // 3. Handle Empty Context
        if (context == null || context.isBlank()) {
            return isValidWithoutContext(response);
        }

        // 4. Deterministic Grounding Checks with Context
        if (!verifyContactAndUrlClaims(response, context)) {
            return false;
        }

        if (!verifyTimeAndScheduleClaims(response, context)) {
            return false;
        }

        if (!verifyNumericalAndCurrencyClaims(response, context)) {
            return false;
        }

        if (!verifyNamedEntitiesAndLocations(response, context)) {
            return false;
        }

        return true;
    }

    /**
     * 1. Refusal check
     */
    private boolean isUnknownOrRefusal(String response) {
        if (response.trim().length() < 120) {
            String lower = response.toLowerCase();
            for (String phrase : UNKNOWN_PHRASES) {
                if (lower.contains(phrase)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * 2. Hedging check
     */
    private boolean isExcessiveHedging(String response) {
        String lower = response.toLowerCase();
        long hedgingCount = HEDGING_PHRASES.stream()
                .filter(lower::contains)
                .count();
        return hedgingCount >= 2;
    }

    /**
     * 3. Handle empty context: allow polite generic greetings, reject specific unsupported facts
     */
    private boolean isValidWithoutContext(String response) {
        // If response mentions specific prices, phone numbers, emails, URLs, or schedules without context, reject
        Set<String> phones = extractPhones(response);
        Set<String> emails = extractEmails(response);
        Set<String> urls = extractUrls(response);
        Set<String> times = extractTimes(response);
        Set<Double> numbers = extractNumbers(response);

        if (!phones.isEmpty() || !emails.isEmpty() || !urls.isEmpty() || !times.isEmpty()) {
            log.warn("[HallucinationDetector] Specific contact/time facts generated without context. Rejecting.");
            return false;
        }

        // Check if specific prices or large quantities are generated without context
        for (Double num : numbers) {
            if (num > 0 && num != 1 && num != 2 && num != 3) {
                log.warn("[HallucinationDetector] Specific numeric fact ({}) generated without context. Rejecting.", num);
                return false;
            }
        }

        return true;
    }

    /**
     * 4. Phone, Email, URL Verification
     */
    private boolean verifyContactAndUrlClaims(String response, String context) {
        // Phones
        Set<String> responsePhones = extractPhones(response);
        Set<String> contextPhones = extractPhones(context);
        for (String phone : responsePhones) {
            if (!contextPhones.contains(phone)) {
                log.warn("[HallucinationDetector] Unsupported phone number: {}", phone);
                return false;
            }
        }

        // Emails
        Set<String> responseEmails = extractEmails(response);
        Set<String> contextEmails = extractEmails(context);
        for (String email : responseEmails) {
            if (!contextEmails.contains(email)) {
                log.warn("[HallucinationDetector] Unsupported email: {}", email);
                return false;
            }
        }

        // URLs
        Set<String> responseUrls = extractUrls(response);
        Set<String> contextUrls = extractUrls(context);
        for (String url : responseUrls) {
            if (!contextUrls.contains(url)) {
                log.warn("[HallucinationDetector] Unsupported URL: {}", url);
                return false;
            }
        }

        return true;
    }

    /**
     * 5. Time & Operating Hours Verification
     */
    private boolean verifyTimeAndScheduleClaims(String response, String context) {
        Set<String> responseTimes = extractTimes(response);
        if (responseTimes.isEmpty()) {
            return true;
        }

        Set<String> contextTimes = extractTimes(context);
        for (String time : responseTimes) {
            if (!contextTimes.contains(time)) {
                log.warn("[HallucinationDetector] Unsupported time/schedule: {} (Context times: {})", time, contextTimes);
                return false;
            }
        }

        // Verify days of week if mentioned specifically
        String lowerResp = response.toLowerCase();
        String lowerCtx = context.toLowerCase();
        for (String day : DAYS_OF_WEEK) {
            if (lowerResp.contains(day) && !lowerCtx.contains(day)) {
                log.warn("[HallucinationDetector] Unsupported day of week: {}", day);
                return false;
            }
        }

        return true;
    }

    /**
     * 6. Number & Currency Verification
     */
    private boolean verifyNumericalAndCurrencyClaims(String response, String context) {
        Set<Double> responseNumbers = extractNumbers(response);
        if (responseNumbers.isEmpty()) {
            return true;
        }

        Set<Double> contextNumbers = extractNumbers(context);
        // Also extract times as numbers to avoid false rejections when 9 is part of 9 AM
        Set<String> contextTimeTokens = extractTimes(context);

        for (Double num : responseNumbers) {
            // Allow small structural numbers (1st, 2, 3) unless it is a specific currency/count
            if (contextNumbers.contains(num)) {
                continue;
            }

            // Check if this number is supported in context words (e.g. "five hundred" -> 500.0)
            if (isNumberSupportedInText(num, context)) {
                continue;
            }

            log.warn("[HallucinationDetector] Unsupported numeric claim: {} (Context numbers: {})", num, contextNumbers);
            return false;
        }

        return true;
    }

    /**
     * 7. Named Entities (Doctors, People, Cities) Verification
     */
    private boolean verifyNamedEntitiesAndLocations(String response, String context) {
        // Check Doctor / Person names
        Set<String> responseDoctors = extractDoctorEntities(response);
        if (!responseDoctors.isEmpty()) {
            Set<String> contextDoctors = extractDoctorEntities(context);
            for (String doc : responseDoctors) {
                if (!contextDoctors.contains(doc) && !context.toLowerCase().contains(doc.toLowerCase())) {
                    log.warn("[HallucinationDetector] Unsupported named entity: {}", doc);
                    return false;
                }
            }
        }

        // Check Major Cities / Locations
        String lowerResp = response.toLowerCase();
        String lowerCtx = context.toLowerCase();
        for (String city : MAJOR_CITIES) {
            if (lowerResp.contains(city) && !lowerCtx.contains(city)) {
                log.warn("[HallucinationDetector] Unsupported city/location: {}", city);
                return false;
            }
        }

        return true;
    }

    // ==========================================
    // EXTRACTION & NORMALIZATION HELPER METHODS
    // ==========================================

    public Set<String> extractPhones(String text) {
        if (text == null) return Collections.emptySet();
        Set<String> result = new HashSet<>();
        Matcher matcher = PHONE_PATTERN.matcher(text);
        while (matcher.find()) {
            String digits = matcher.group().replaceAll("[^0-9]", "");
            if (digits.length() >= 7 && digits.length() <= 15) {
                result.add(digits);
            }
        }
        return result;
    }

    public Set<String> extractEmails(String text) {
        if (text == null) return Collections.emptySet();
        Set<String> result = new HashSet<>();
        Matcher matcher = EMAIL_PATTERN.matcher(text);
        while (matcher.find()) {
            result.add(matcher.group().toLowerCase());
        }
        return result;
    }

    public Set<String> extractUrls(String text) {
        if (text == null) return Collections.emptySet();
        Set<String> result = new HashSet<>();
        Matcher matcher = URL_PATTERN.matcher(text);
        while (matcher.find()) {
            String url = matcher.group().toLowerCase()
                    .replaceFirst("^https?://", "")
                    .replaceFirst("^www\\.", "")
                    .replaceAll("/$", "");
            result.add(url);
        }
        return result;
    }

    public Set<String> extractTimes(String text) {
        if (text == null) return Collections.emptySet();
        Set<String> times = new HashSet<>();
        Matcher matcher = TIME_PATTERN.matcher(text);
        while (matcher.find()) {
            String match = matcher.group().trim().toLowerCase();
            String normalized = normalizeTime(match);
            if (normalized != null) {
                times.add(normalized);
            }
        }
        return times;
    }

    public String normalizeTime(String rawTime) {
        if (rawTime == null) return null;
        String t = rawTime.toLowerCase().trim()
                .replaceAll("\\s+", " ")
                .replace("a.m.", "am")
                .replace("p.m.", "pm");

        // "9 in the morning" -> "09:00"
        if (t.contains("in the morning")) {
            String hour = t.replaceAll("[^0-9]", "").trim();
            if (!hour.isEmpty()) {
                int h = Integer.parseInt(hour);
                return String.format("%02d:00", h);
            }
        }
        // "6 in the evening" / "in the afternoon" / "in the night"
        if (t.contains("in the evening") || t.contains("in the afternoon") || t.contains("in the night")) {
            String hour = t.replaceAll("[^0-9]", "").trim();
            if (!hour.isEmpty()) {
                int h = Integer.parseInt(hour);
                if (h < 12) h += 12;
                return String.format("%02d:00", h);
            }
        }

        // "9 am" or "9:00 am" or "6 pm"
        if (t.contains("am") || t.contains("pm")) {
            boolean isPm = t.contains("pm");
            String clean = t.replace("am", "").replace("pm", "").trim();
            int hour = 0;
            int minute = 0;
            if (clean.contains(":")) {
                String[] parts = clean.split(":");
                hour = Integer.parseInt(parts[0].trim());
                minute = Integer.parseInt(parts[1].trim());
            } else {
                hour = Integer.parseInt(clean.trim());
            }
            if (isPm && hour < 12) hour += 12;
            if (!isPm && hour == 12) hour = 0;
            return String.format("%02d:%02d", hour, minute);
        }

        // 24hr format "18:00"
        if (t.contains(":")) {
            String[] parts = t.split(":");
            int hour = Integer.parseInt(parts[0].trim());
            int minute = Integer.parseInt(parts[1].trim());
            return String.format("%02d:%02d", hour, minute);
        }

        return t;
    }

    public Set<Double> extractNumbers(String text) {
        if (text == null || text.isBlank()) return Collections.emptySet();
        Set<Double> numbers = new HashSet<>();

        // Strip times, phones, and URLs first to avoid extracting time/phone digits as currency/quantities
        String workingText = text;
        workingText = TIME_PATTERN.matcher(workingText).replaceAll(" ");
        workingText = PHONE_PATTERN.matcher(workingText).replaceAll(" ");
        workingText = URL_PATTERN.matcher(workingText).replaceAll(" ");

        // 1. Word numbers sorted by length descending ("five hundred" before "five")
        String lowerWorkingText = workingText.toLowerCase();
        List<Map.Entry<String, Integer>> sortedWordEntries = new ArrayList<>(WORD_TO_NUMBER.entrySet());
        sortedWordEntries.sort((a, b) -> Integer.compare(b.getKey().length(), a.getKey().length()));

        for (Map.Entry<String, Integer> entry : sortedWordEntries) {
            Pattern wordPattern = Pattern.compile("\\b" + Pattern.quote(entry.getKey()) + "\\b");
            Matcher wordMatcher = wordPattern.matcher(lowerWorkingText);
            if (wordMatcher.find()) {
                numbers.add(entry.getValue().doubleValue());
                lowerWorkingText = wordMatcher.replaceAll(" ");
            }
        }

        // 2. Regex number & currency extraction from remaining cleaned text
        Matcher matcher = CURRENCY_NUMBER_PATTERN.matcher(lowerWorkingText);
        while (matcher.find()) {
            String numStr = matcher.group(1);
            if (numStr != null && !numStr.isBlank()) {
                try {
                    String clean = numStr.replace(",", "");
                    double val = Double.parseDouble(clean);
                    // Filter out years (like 2024, 2025, 2026) unless explicitly prefixed with currency
                    if (val >= 2020 && val <= 2030 && !text.contains("₹") && !text.contains("$") && !text.contains("Rs")) {
                        continue;
                    }
                    numbers.add(val);
                } catch (NumberFormatException ignored) {}
            }
        }

        return numbers;
    }

    private boolean isNumberSupportedInText(Double num, String text) {
        if (text == null) return false;
        String lower = text.toLowerCase();
        for (Map.Entry<String, Integer> entry : WORD_TO_NUMBER.entrySet()) {
            if (entry.getValue().doubleValue() == num.doubleValue()) {
                if (lower.matches(".*\\b" + Pattern.quote(entry.getKey()) + "\\b.*")) {
                    return true;
                }
            }
        }
        return false;
    }

    public Set<String> extractDoctorEntities(String text) {
        if (text == null) return Collections.emptySet();
        Set<String> doctors = new HashSet<>();
        Matcher matcher = DOCTOR_ENTITY_PATTERN.matcher(text);
        while (matcher.find()) {
            doctors.add(matcher.group().trim());
        }
        return doctors;
    }
}
