ALTER TABLE leads ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS interest_category VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS last_score_calculated_at TIMESTAMP;
