-- V10043: Add human-readable lead_number column to leads table
-- Format: first 4 letters of business name (uppercase) + hyphen + 4-digit sequence
-- Example: GYAN-0001, DENT-0042
-- Generated by application on lead creation; NULL for existing leads (backfill not required)

ALTER TABLE leads ADD COLUMN IF NOT EXISTS lead_number VARCHAR(20);

-- Index for fast lookup by lead number (e.g. search in CRM dashboard)
CREATE INDEX IF NOT EXISTS idx_leads_lead_number ON leads (lead_number);
