-- V10044: Add human-readable reference_number columns to appointments, bookings, and tickets
-- Format: {PREFIX}-{TYPE}-{YYYYMMDD}-{NNNN}
-- Examples:
--   GYAN-A-20250520-0001 (Appointment)
--   GYAN-B-20250520-0001 (Booking)
--   GYAN-T-20250520-0001 (Ticket)
-- Generated by application on entity creation; NULL for existing records (backfill not required)

-- Add reference_number to appointments table
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS reference_number VARCHAR(30);
CREATE INDEX IF NOT EXISTS idx_appointments_reference_number ON appointments (reference_number);

-- Add reference_number to bookings table
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS reference_number VARCHAR(30);
CREATE INDEX IF NOT EXISTS idx_bookings_reference_number ON bookings (reference_number);

-- Add reference_number to tickets table
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS reference_number VARCHAR(30);
CREATE INDEX IF NOT EXISTS idx_tickets_reference_number ON tickets (reference_number);
