ALTER TABLE lead_enquiries 
ADD COLUMN name VARCHAR(255),
ADD COLUMN email VARCHAR(255),
ADD COLUMN phone VARCHAR(50),
ADD COLUMN company VARCHAR(255),
ADD COLUMN service_category VARCHAR(255),
ADD COLUMN requirement TEXT,
ADD COLUMN budget VARCHAR(255),
ADD COLUMN city VARCHAR(255),
ADD COLUMN country VARCHAR(255);
