ALTER TABLE lead_enquiries
ADD COLUMN IF NOT EXISTS age VARCHAR(255),
ADD COLUMN IF NOT EXISTS gender VARCHAR(255),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS pincode VARCHAR(255),
ADD COLUMN IF NOT EXISTS preferred_date VARCHAR(255);
